### ISSUE TITLE
アイコン

### ISSUE THREAD

**Issue by mizucoffee** [sukesan1984/agrarian#110]
自分でも適当さに泣く
![a](https://cloud.githubusercontent.com/assets/9247699/9411835/6163795c-4863-11e5-9a1d-06e43afcc962.png)
![b](https://cloud.githubusercontent.com/assets/9247699/9411836/616f3f08-4863-11e5-91e2-1211481a45b3.png)
てきとーにクローズしてもらって結構です。
サイズとか的にファビコンにしか出来なさそう。
木こりから着想を得て。

**Comment by sukesan1984** [comment]
favicon.icoにしたよ。

**Comment by sukesan1984** [comment]
ty

**Comment by MaxMEllon** [comment]
いいかんじ！すげー！

@KawakawaRitsuki :+1: +1
