### ISSUE TITLE
githubを使ってない人にもissueかけるようにしたい。

### ISSUE THREAD

**Issue by sukesan1984** [sukesan1984/agrarian#167]

**Comment by MaxMEllon** [comment]
きつくね？

**Comment by mizucoffee** [comment]
issueじゃなくても、お問い合せとか意見的なそんな感じのフォームがあると楽かなって思いました。

**Comment by MaxMEllon** [comment]
なるほど。   wikiじゃきつそう？

**Comment by MaxMEllon** [comment]
クライアント作って
https://developer.github.com/v3/issues/#create-an-issue
このpostなげたら作れるけど開発リソースと得られるメリットが無い感

**Comment by mizucoffee** [comment]
Wikiも結局多少の知識とか、みんなに見られると思うと嫌な人もいるかなと。
Postでできることは出来るんですね。。。

**Comment by MaxMEllon** [comment]
つくります。

**Comment by sukesan1984** [comment]
+1

**Comment by MaxMEllon** [comment]
https://issue-submit-form-for-agrarian.herokuapp.com/issues/new

ざっとかんせい

**Comment by sukesan1984** [comment]
+++
