### ISSUE TITLE
uikit-sass-rails自体のバグがあるらしい。

### ISSUE THREAD

**Issue by sukesan1984** [sukesan1984/agrarian#19]
jsが一部動かないらしい。

**Comment by MaxMEllon** [comment]
おそらく，
 vendor/assets/javascripts/uikit.js
の37行目，38行目入れ替えで直ります．

slideshowを読み込む前にslideshow-fxを読み込んでるっぽいですね．

gem 'uikit-sass-rails', git: 'git://github.com/8398a7/uikit-sass-rails'
コッチのuikitを使うとより確実です．

**Comment by sukesan1984** [comment]
なるほどー
