### ISSUE TITLE
[suggest] issueの管理方法の提案

### ISSUE THREAD

**Issue by MaxMEllon** [sukesan1984/agrarian#34]
- 必須機能には enhancement ラベルを付ける
- 要望機能（優先度低め）のものには suggest ラベルを付ける

@KawakawaRitsuki  さんが幾つかアイデアをだしてくださっているので ，
それらを実装するかどうか，どの段階で実装するか の返答もしておいたほうが良いと思います．

> 放送を見れていないので流れを理解していませんが．余計なお世話でしたらこのissueをクローズしていただけると幸いです．

**Comment by sukesan1984** [comment]
そうですね。
とりあえず突っ込んでおいてもらえれば後々棚卸しします（ワロ）

**Comment by sukesan1984** [comment]
その時にテンション上がったら作る感じのゆるふわな感じでやっていきたいと思ってます。
あんまりかっちりタスク管理とかしだすと辛いので・・（ワラ

**Comment by mizucoffee** [comment]
それでいいと思いますよー！
がんばれです！

**Comment by MaxMEllon** [comment]
ゆるふわクローズ

**Comment by sukesan1984** [comment]
提案ありがとうございます！！
